// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEOI5gIa1yIrNSM8_-V_8wxqdjVT3SsX8',
    appId: '1:407440468402:web:2637dad193325c431adcab',
    messagingSenderId: '407440468402',
    projectId: 'flutter-firebase-29e73',
    authDomain: 'flutter-firebase-29e73.firebaseapp.com',
    storageBucket: 'flutter-firebase-29e73.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGe6ucNkA_-x8IuTGeCKvSvesXB63gcQw',
    appId: '1:407440468402:android:c5d49cee57e729cf1adcab',
    messagingSenderId: '407440468402',
    projectId: 'flutter-firebase-29e73',
    storageBucket: 'flutter-firebase-29e73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyXXmUQtLUatIETY5HD4iHAUHSNXVoZn8',
    appId: '1:407440468402:ios:823f4cd360a269301adcab',
    messagingSenderId: '407440468402',
    projectId: 'flutter-firebase-29e73',
    storageBucket: 'flutter-firebase-29e73.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyXXmUQtLUatIETY5HD4iHAUHSNXVoZn8',
    appId: '1:407440468402:ios:af445a8590bf819f1adcab',
    messagingSenderId: '407440468402',
    projectId: 'flutter-firebase-29e73',
    storageBucket: 'flutter-firebase-29e73.appspot.com',
    iosBundleId: 'com.example.finalProject.RunnerTests',
  );
}
